version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3399:3306"
    volumes: 
      - .data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser    
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: helium-php7
    ports:
      - 8081:80
    volumes:
      - .:/app